server:
  port: 612

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    platform: postgres

  sql:
    init:
      schema-locations: classpath:/schema-postgresql.sql
      mode: always
      platform: postgres
